name: Release
run-name: Release
on:
  pull_request:
    branch: dev
    types: [closed]
jobs:
  Test:
    if: github.event.pull_request.merged == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm ci
      - name: WiP tests
        run: echo "We should launch e2e tests here"

  TagAsStable:
    if: github.event.pull_request.merged == 'true'
    needs: Test
    runs-on: ubuntu-latest
    steps:
      uses: actions/github-script@v5
      with:
        script: |
          github.rest.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: 'refs/tags/stable',
            sha: context.sha
          })
